title: Your Site Title

theme: jekyll-theme-minimal

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  # Footer customization
footer:
  show_credits: false

